# Generated by Django 4.1.2 on 2022-10-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=25, unique=True)),
                ('evalue', models.IntegerField(max_length=20)),
                ('edate', models.TimeField()),
            ],
        ),
    ]
