# Generated by Django 4.1.2 on 2022-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ManyToManyField(to='moneyapp.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='edate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='evalue',
            field=models.IntegerField(),
        ),
    ]
