# Generated by Django 4.1.2 on 2022-10-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0003_expense_category_alter_expense_edate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
