# Generated by Django 4.1.2 on 2022-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0004_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=25, unique=True)),
                ('evalue', models.IntegerField()),
                ('edate', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='moneyapp.category')),
            ],
        ),
    ]
